language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kylecribbs
  on:
    tags: true
    repo: kylecribbs/archer_tools
    python: 3.7
  password:
    secure: aqlC7i7KKCutcgc0h/Y1Lkb6M4ZS4hZjGXnJRR0+w1cVOaabPzM9X077jONP7hX5DTdMjwUqicTgP5vpdlN+XPOwa0uZ74fZtDO7pc+yBaPsVIxrt3MQ0PYkV1rVuMuHt69AkGhSEJGTiTYDmiuaAFwksivHLorLCfwQFSV4tRuvGjU7r73lj9AGnbrG4d/RPMXM1hWVlfXgFOeeyXXH8aE+M2cPcByAURpz9H1LtadeeFYDpK4f13+EUPh4WdFusNsdwyx/6uczZXIzp111YRSRP1M03mm7IZwGwae3FDdyKOy6sxzuvqXzUln1LPbKrdV7N2f9D3UhWTdcNIsCKWPHdj5CktULx4tpPBkjsSYlcvb7w9b7Mq70ekNzeB8XVbGm4eVynyH/RFhkx6zPUWZa/HwbJTyCh5tKsGsveUNLo9uP6oLmuFGIPtz22EfZuNz4+3ulP4I0NnprvsaslBR1SStUDZ1eRBcDrgSQv3Oh85xDrrgqLMHu+ZB44611TCTHQk/826DIsRg5SloCuga7wE9HcR6tb65k848jPlgpnOwSPhXXoJ0zBxcWhbgOd9BhqGCBZUOjMAoCFvDNlmkzvOt9M4GlFQWzz4ThEIwKH04HhvuXo0y5g1Af7+JgWkE8cfOrtVTUc4knqun6Pjf855ySM2zCubi2LGtxcOM=
