language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kylecribbs
  on:
    repo: kylecribbs/archer_tools
    python: 3.7
  password:
    secure: JqO3COvIMXCH4zYwvmPN6/WfGkdYAhhqwUhVGKLy86Tqq1EPV3/wBzkOnl6yZl5c3OfOIcCYlS7qTgjV4X8+BHpjuU7XH9ef7u0C5O3plzM8efBGDXyrNcUvVvuqt+onmZbyEvS8AXivfCCbjcjw67YD/segjpAP42tMmgHuETwYbbzHPDN+4BeLyf+p/Pyi7eE1Tje2D3tqGPbmhEKg5MrYJqT4wu8/DIBzniPuHG6BMzcrpL7yDN4K6lCgou9BSeZXCcQk/fBCMALOvjeaVs8TwzIW1ly8UQVrmcm9peY5P6ZgjecCakASUhpstWNE0e7IbAwAAahvjgYcTlp9wIFKM97Ja492n0Q87O+aKjN29kOh8yIUcFXzyvTBvH3/ft6eQaJfyAu/H+6P9IgfXQm3vyhIakgd4m7XgmNKRNJtT8h6CbExar6kH21b6AdluUZXhkbox5K4ZKq6tDqo5s18uKBXP1znnFMwL7q4BIdMww2rn/pltapZ5Aa1TFAlBUfng37DZbDPkFB+3pJG3HaJ/ap5iI6JTjBDfbld22U9AP+CEplWNPLf15QNc+uCJxkHOXDoEGcnDRVgdQxTbrhkta9e9xB1yKCG8bPmYBpzKVLX04lTmV49207//Q8hxzZ9Dxgaky+OeF09N+NdwmLUXdeFqWYdGvTVfP7PW50=
